### ISSUE TITLE
Remove this feedstock

### ISSUE THREAD

**Issue by igortg** [conda-forge/flask-rest-orm-feedstock#8]
Feedstock was renamed to `flask-restlachemy`. Do we remove the old feedstock after renaming @conda-forge/core ?

**Comment by isuruf** [comment]
> Feedstock was renamed to flask-restlachemy

What do you mean? I don't see any flask-restlachemy-feedstock

**Comment by igortg** [comment]
Sorry, i misspelled *restalchemy*:
https://github.com/conda-forge/flask-restalchemy-feedstock

**Comment by isuruf** [comment]
I'll archive this github repo
